# Generated by Django 4.2.6 on 2023-10-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
